# Generated by Django 4.2.13 on 2024-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('taskImage', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
