# Generated by Django 4.2.13 on 2024-10-24 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertasks',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usertasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
